### ISSUE TITLE
[已解决] Android版Aria2状态显示 未连接

### ISSUE THREAD

**Issue by youko-lib** [Xmader/aria-ng-gui-android#1]
解决方案：
    手动给予 存储空间读写 的权限

---
bug表现为，程序没有显式请求存储空间读写的权限。
在首次给予该权限前Aria2状态一直显示未连接。
猜测可能是无法写入配置文件，给予该权限后一切功能正常。

**Comment by keniji** [comment]
手动给与权限后本地aria2（6800）显示连接，但无法连接添加的其他PRC。我的PRC是搭在群晖上的，使用https协议并设置了PRC密钥验证。通过同样群晖上搭的Aria2 WebUI，还有Chrome上的AriaNg连接都正常。检查手机存储的Android/data/com.xmader.aria_ng_gui_android发现还是空的（两个空文件夹），不知道是否有关（因为懒得root了），目前仍未找到解决方案。

**Comment by Xmader** [comment]
您好，这个问题在最新的 `v1.1.1` 版本中已经修复
https://github.com/Xmader/aria-ng-gui-android/releases/tag/v1.1.1
