### ISSUE TITLE
AriaNG Access to sd card(Android)

### ISSUE THREAD

**Issue by vpn12** [Xmader/aria-ng-gui-android#11]
Downloading cannot be done in sd card (by changing download path) as it has no access to SD card. A permission for WRITE_EXTERNAL_STORAGE is required so that it can download files to SD card like the way we download files to SD card from browsers like Chrome in Android. In today's time, it is an important feature to download big files to SD card. Pls fix this.

Regards,
vpn12

**Comment by Xmader** [comment]
It's already there.
https://github.com/Xmader/aria-ng-gui-android/blob/ddb03d82e5632350d453fdf9defe3f69f5ff1d95/src/main.js#L95-L113

**Comment by vpn12** [comment]
> It's already there.
> https://github.com/Xmader/aria-ng-gui-android/blob/ddb03d82e5632350d453fdf9defe3f69f5ff1d95/src/main.js#L95-L113

Yeah, I have already fix this. Only the sd card directory i.e. /storage/342D-B935/Android/data/com.xmader.aria_ng_gui_android/files is working as it is accessible for every app. Well it's working fine. Btw there is an update in ariang in which there is a option of dark theme in AriaNg settings. Do you have any plans to update the app ? I am also working on it. I have to simply do some changes in index.html

Btw thanks for you reply
Regards,
vpn12

**Comment by Xmader** [comment]
> Do you have any plans to update the app?

I've released version 1.3.1 that upgrades the builtin AriaNg
