### ISSUE TITLE
不支持bt种子下载吗？

### ISSUE THREAD

**Issue by zhiting9420** [Xmader/aria-ng-gui-android#19]
是不是不支持bt种子下载？

**Comment by Xmader** [comment]
支持的

![Screenshot from 2021-08-19 22-58-34](https://user-images.githubusercontent.com/16057139/130172441-e712fac5-abf4-423f-9cf5-09f5e3e3fb7d.png)

**Comment by zhiting9420** [comment]
好的 可以了
