### ISSUE TITLE
1.2在哪里下载

### ISSUE THREAD

**Issue by a2212997715** [Xmader/aria-ng-gui-android#5]
只看到一个zip的
没有apk安装包

**Comment by Xmader** [comment]
不好意思，CI 可能配置错误，apk 没有被传上去，一会看一下和补传

**Comment by Xmader** [comment]
不好意思，CI 可能配置错误，apk 没有被传上去，一会看一下和补传

On Oct. 18, 2019 11:27, a2212997715 <notifications@github.com> wrote:

只看到一个zip的
没有apk安装包
